### ISSUE TITLE
Critical vulnerabilities

### ISSUE THREAD

**Issue by henriksegalt** [horizon-ui/shadcn-boilerplate-pro-issues#2]
up to date, audited 1297 packages in 4s

264 packages are looking for funding
  run `npm fund` for details

# npm audit report

babel-traverse  *
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
No fix available
node_modules/babel-traverse
  babel-core  5.8.20 - 7.0.0-beta.3
  Depends on vulnerable versions of babel-helpers
  Depends on vulnerable versions of babel-register
  Depends on vulnerable versions of babel-template
  Depends on vulnerable versions of babel-traverse
  Depends on vulnerable versions of json5
  node_modules/babel-core
    babel-cli  *
    Depends on vulnerable versions of babel-core
    Depends on vulnerable versions of babel-register
    Depends on vulnerable versions of chokidar
    node_modules/babel-cli
    babel-register  *
    Depends on vulnerable versions of babel-core
    node_modules/babel-register
  babel-helper-call-delegate  *
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-helper-call-delegate
  babel-helper-function-name  *
  Depends on vulnerable versions of babel-template
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-helper-function-name
    babel-helper-define-map  *
    Depends on vulnerable versions of babel-helper-function-name
    node_modules/babel-helper-define-map
    babel-plugin-transform-es2015-function-name  *
    Depends on vulnerable versions of babel-helper-function-name
    node_modules/babel-plugin-transform-es2015-function-name
  babel-helper-replace-supers  *
  Depends on vulnerable versions of babel-template
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-helper-replace-supers
    babel-plugin-transform-es2015-object-super  *
    Depends on vulnerable versions of babel-helper-replace-supers
    node_modules/babel-plugin-transform-es2015-object-super
  babel-plugin-transform-es2015-block-scoping  *
  Depends on vulnerable versions of babel-template
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-plugin-transform-es2015-block-scoping
  babel-plugin-transform-es2015-classes  *
  Depends on vulnerable versions of babel-helper-define-map
  Depends on vulnerable versions of babel-helper-function-name
  Depends on vulnerable versions of babel-helper-replace-supers
  Depends on vulnerable versions of babel-template
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-plugin-transform-es2015-classes
    babel-preset-es2015  *
    Depends on vulnerable versions of babel-plugin-transform-es2015-block-scoping
    Depends on vulnerable versions of babel-plugin-transform-es2015-classes
    Depends on vulnerable versions of babel-plugin-transform-es2015-computed-properties
    Depends on vulnerable versions of babel-plugin-transform-es2015-function-name
    Depends on vulnerable versions of babel-plugin-transform-es2015-modules-amd
    Depends on vulnerable versions of babel-plugin-transform-es2015-modules-commonjs
    Depends on vulnerable versions of babel-plugin-transform-es2015-modules-systemjs
    Depends on vulnerable versions of babel-plugin-transform-es2015-modules-umd
    Depends on vulnerable versions of babel-plugin-transform-es2015-object-super
    Depends on vulnerable versions of babel-plugin-transform-es2015-parameters
    node_modules/babel-preset-es2015
  babel-plugin-transform-es2015-parameters  *
  Depends on vulnerable versions of babel-helper-call-delegate
  Depends on vulnerable versions of babel-template
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-plugin-transform-es2015-parameters
  babel-template  *
  Depends on vulnerable versions of babel-traverse
  node_modules/babel-template
    babel-helpers  *
    Depends on vulnerable versions of babel-template
    node_modules/babel-helpers
    babel-plugin-transform-es2015-computed-properties  *
    Depends on vulnerable versions of babel-template
    node_modules/babel-plugin-transform-es2015-computed-properties
    babel-plugin-transform-es2015-modules-amd  *
    Depends on vulnerable versions of babel-plugin-transform-es2015-modules-commonjs
    Depends on vulnerable versions of babel-template
    node_modules/babel-plugin-transform-es2015-modules-amd
      babel-plugin-transform-es2015-modules-umd  *
      Depends on vulnerable versions of babel-plugin-transform-es2015-modules-amd
      Depends on vulnerable versions of babel-template
      node_modules/babel-plugin-transform-es2015-modules-umd
    babel-plugin-transform-es2015-modules-commonjs  <=7.0.0-beta.0
    Depends on vulnerable versions of babel-template
    node_modules/babel-plugin-transform-es2015-modules-commonjs
    babel-plugin-transform-es2015-modules-systemjs  *
    Depends on vulnerable versions of babel-template
    node_modules/babel-plugin-transform-es2015-modules-systemjs

braces  <=2.3.0
Regular Expression Denial of Service in braces - https://github.com/advisories/GHSA-g95f-p29q-9xw4
Regular Expression Denial of Service (ReDoS) in braces - https://github.com/advisories/GHSA-cwfw-4gq5-mrqx
fix available via `npm audit fix`
node_modules/braces
  micromatch  0.2.0 - 2.3.11
  Depends on vulnerable versions of braces
  Depends on vulnerable versions of parse-glob
  node_modules/micromatch
    anymatch  1.2.0 - 1.3.2
    Depends on vulnerable versions of micromatch
    node_modules/anymatch
      chokidar  1.0.0-rc1 - 2.1.8
      Depends on vulnerable versions of anymatch
      Depends on vulnerable versions of glob-parent
      node_modules/chokidar

glob-parent  <5.1.2
Severity: high
glob-parent vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/glob-parent
  glob-base  *
  Depends on vulnerable versions of glob-parent
  node_modules/glob-base
    parse-glob  >=2.1.0
    Depends on vulnerable versions of glob-base
    node_modules/parse-glob

json5  <1.0.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
No fix available
node_modules/babel-core/node_modules/json5

29 vulnerabilities (2 low, 8 high, 19 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

**Comment by simmmpleweb** [comment]
Hello, @henriksegalt ! Thank you for supporting Horizon. We fixed those issues, I will ping you when we push the final archive after all testing is good.

**Comment by simmmpleweb** [comment]
Fixed! @henriksegalt

**Comment by henriksegalt** [comment]
Is the package ready to download?
