### ISSUE TITLE
@supabase/auth-helpers-nextjs

### ISSUE THREAD

**Issue by henriksegalt** [horizon-ui/shadcn-boilerplate-pro-issues#3]
Supabase recommends to switch to @supabase/ssr

**Comment by henriksegalt** [comment]
This repo has the updated code:
https://github.com/vercel/nextjs-subscription-payments

**Comment by henriksegalt** [comment]
Adding a screenshot of the depreciation error in the code,
![supabase_auth_warning](https://github.com/horizon-ui/shadcn-boilerplate-pro-issues/assets/104114447/a1577c54-b501-47ec-a62f-45353d141e59)

**Comment by simmmpleweb** [comment]
We are currently working on updating our products to supabase/ssr, you will be the first one to get pinged when it drops!
Thank you, Vlad.

**Comment by henriksegalt** [comment]
Thanks, what is the time frame for that?

**Comment by henriksegalt** [comment]
You should also consider using next middleware for access control.

**Comment by simmmpleweb** [comment]
@henriksegalt we updated the product to @supabase/ssr!
