### ISSUE TITLE
../ui/ folder missing from download?

### ISSUE THREAD

**Issue by henriksegalt** [horizon-ui/shadcn-boilerplate-pro-issues#4]
./components/landing/feature-one.tsx:3:1
Module not found: Can't resolve '../ui/badge'
  1 | 'use client';
  2 |
> 3 | import { Badge } from '../ui/badge';
    | ^

**Comment by simmmpleweb** [comment]
This is fixed by using  `npx shadcn-ui@latest add --all` command. Somehow it slipped the documentation, we will add it ASAP.
Regards, Vlad
